import {
  OfflineManager,
  type OfflinePackError,
  type OfflinePack,
  type OfflinePackProgressListener,
  type OfflinePackErrorListener,
  type OfflinePackStatus,
} from '@maplibre/maplibre-react-native';

export type OfflineMapPackMetadata = {
  /** User-facing label, e.g. "Las Vegas Area". */
  name: string;
  /** ISO timestamp of when this pack was created. */
  createdAt: string;
  radiusMiles: number;
  centerLng: number;
  centerLat: number;
};

export type OfflineMapPack = {
  /** UUID auto-generated by MapLibre. */
  id: string;
  metadata: OfflineMapPackMetadata;
  status: OfflinePackStatus;
};

export type ProgressHandler = (
  pack: OfflinePack,
  status: OfflinePackStatus,
) => void;
export type ErrorHandler = (pack: OfflinePack, error: OfflinePackError) => void;

/** OpenFreeMap Liberty style — free, OSM-backed, no API key required. */
export const OPENFREEMAP_STYLE = 'https://tiles.openfreemap.org/styles/liberty';

/**
 * Default zoom range for the ~50mi prepper-grade offline pack.
 * z8–13 gives street-level detail without exploding storage.
 */
export const DEFAULT_OFFLINE_ZOOM = { min: 8, max: 13 } as const;

/** "High detail" toggle includes z14 (~2× storage). */
export const HIGH_DETAIL_OFFLINE_ZOOM = { min: 8, max: 14 } as const;

// ---------------------------------------------------------------------------
// Tile-count math (Web Mercator / "slippy map" tile coordinates)
// Note: does not handle antimeridian-crossing bounds (fine for US-only use).
// ---------------------------------------------------------------------------

function lonToTileX(lon: number, z: number): number {
  return Math.floor(((lon + 180) / 360) * Math.pow(2, z));
}

function latToTileY(lat: number, z: number): number {
  const rad = (lat * Math.PI) / 180;
  return Math.floor(
    ((1 - Math.log(Math.tan(rad) + 1 / Math.cos(rad)) / Math.PI) / 2) *
      Math.pow(2, z),
  );
}

function tileCountForBoundsAtZoom(
  [west, south, east, north]: number[],
  z: number,
): number {
  const x0 = lonToTileX(west, z);
  const x1 = lonToTileX(east, z);
  const y0 = latToTileY(north, z); // tile Y is inverted (north → smaller index)
  const y1 = latToTileY(south, z);
  return (Math.abs(x1 - x0) + 1) * (Math.abs(y1 - y0) + 1);
}

/**
 * Per-zoom average tile sizes for OpenMapTiles-schema vector tiles (urban-biased,
 * which is appropriate for offline packs centred on populated areas).
 * Source: empirical OpenMapTiles benchmark data.
 * Tiles at low zooms are large (regional data) then shrink at mid zooms as
 * generalisation reduces features, then grow again at z14 as building
 * footprints are added.
 */
const AVG_TILE_BYTES_BY_ZOOM: Readonly<Record<number, number>> = {
  0:  14_000,
  1:  86_000,
  2:  77_000,
  3:  34_000,
  4:  23_000,
  5:   7_000,
  6:   8_000,
  7:   8_000,
  8:   7_000,
  9:   6_000,
  10:  3_000,
  11:  1_000,
  12:  2_000,
  13:  2_000,
  14:  5_000,
};

/** Fallback for zoom levels outside the table (e.g. z15+). */
const DEFAULT_AVG_TILE_BYTES = 3_000;

function avgTileBytesForZoom(z: number): number {
  return AVG_TILE_BYTES_BY_ZOOM[z] ?? DEFAULT_AVG_TILE_BYTES;
}

// ---------------------------------------------------------------------------
// Service
// ---------------------------------------------------------------------------

/**
 * Thin, strongly-typed wrapper around MapLibre's `OfflineManager`.
 *
 * All offline-map operations in UI code must go through this service —
 * never import `OfflineManager` from `@maplibre/maplibre-react-native` directly
 * outside of this file.
 */
export const OfflineMapService = {
  /**
   * Create and start downloading an offline pack covering the given bounds.
   * Returns the created pack including its auto-generated UUID `id`.
   */
  async downloadRegion(args: {
    bounds: [west: number, south: number, east: number, north: number];
    metadata: OfflineMapPackMetadata;
    zoomRange?: { min: number; max: number };
    onProgress?: ProgressHandler;
    onError?: ErrorHandler;
  }): Promise<OfflinePack> {
    const zoom = args.zoomRange ?? DEFAULT_OFFLINE_ZOOM;

    // The v11 API marks both listeners as required; fall back to no-ops so we
    // never pass undefined past the type boundary.
    const progressListener: OfflinePackProgressListener =
      (args.onProgress as OfflinePackProgressListener | undefined) ?? (() => {});
    const errorListener: OfflinePackErrorListener =
      (args.onError as OfflinePackErrorListener | undefined) ?? (() => {});

    return OfflineManager.createPack(
      {
        mapStyle: OPENFREEMAP_STYLE,
        bounds: args.bounds,
        minZoom: zoom.min,
        maxZoom: zoom.max,
        metadata: args.metadata,
      },
      progressListener,
      errorListener,
    );
  },

  async listPacks(): Promise<OfflineMapPack[]> {
    const packs = await OfflineManager.getPacks();
    return packs.map(p => ({
      id: p.id,
      metadata: p.metadata as OfflineMapPackMetadata,
      status: p.status,
    }));
  },

  async getPack(id: string): Promise<OfflineMapPack | undefined> {
    const pack = await OfflineManager.getPack(id);
    if (!pack) return undefined;
    return {
      id: pack.id,
      metadata: pack.metadata as OfflineMapPackMetadata,
      status: pack.status,
    };
  },

  async deletePack(id: string): Promise<void> {
    OfflineManager.removeListener(id); // safe even if no listener is registered
    await OfflineManager.deletePack(id);
  },

  /**
   * Re-attach progress/error listeners to an in-flight pack.
   * Useful after the app is backgrounded and foregrounded again.
   */
  async subscribe(
    id: string,
    onProgress: ProgressHandler,
    onError: ErrorHandler,
  ): Promise<void> {
    await OfflineManager.addListener(
      id,
      onProgress as OfflinePackProgressListener,
      onError as OfflinePackErrorListener,
    );
  },

  unsubscribe(id: string): void {
    OfflineManager.removeListener(id);
  },

  /**
   * Estimate the download size in bytes for a given bounds + zoom range.
   *
   * Uses per-zoom average tile sizes derived from empirical OpenMapTiles
   * benchmark data (urban-biased). For a ~50-mile radius urban area at
   * z8–13 this produces ~10–40 MB; at z8–14 roughly 2× that.
   */
  estimateDownloadBytes(args: {
    bounds: [west: number, south: number, east: number, north: number];
    zoomRange: { min: number; max: number };
  }): number {
    const [west, south, east, north] = args.bounds;
    let totalBytes = 0;
    for (let z = args.zoomRange.min; z <= args.zoomRange.max; z++) {
      totalBytes +=
        tileCountForBoundsAtZoom([west, south, east, north], z) *
        avgTileBytesForZoom(z);
    }
    return totalBytes;
  },
};
