import {
  OfflineManager,
  type OfflinePackError,
  type OfflinePackErrorListener,
  type OfflinePack,
  type OfflinePackProgressListener,
  type OfflinePackStatus,
} from '@maplibre/maplibre-react-native';

export type OfflineMapPackMetadata = {
  /** User-facing label, e.g. "Las Vegas Area". */
  name: string;
  /** ISO timestamp of when this pack was created. */
  createdAt: string;
  radiusMiles: number;
  centerLng: number;
  centerLat: number;
};

export type OfflineMapPack = {
  /** UUID auto-generated by MapLibre. */
  id: string;
  metadata: OfflineMapPackMetadata;
  status: OfflinePackStatus;
};

export type ProgressHandler = (
  pack: OfflinePack,
  status: OfflinePackStatus,
) => void;
export type ErrorHandler = (pack: OfflinePack, error: OfflinePackError) => void;

/** OpenFreeMap Liberty style — free, OSM-backed, no API key required. */
export const OPENFREEMAP_STYLE = 'https://tiles.openfreemap.org/styles/liberty';

/**
 * Default zoom range for the ~50mi prepper-grade offline pack.
 * z8–13 gives street-level detail without exploding storage.
 */
export const DEFAULT_OFFLINE_ZOOM = { min: 8, max: 13 } as const;

/** "High detail" toggle includes z14 (~2× storage). */
export const HIGH_DETAIL_OFFLINE_ZOOM = { min: 8, max: 14 } as const;

// ---------------------------------------------------------------------------
// Tile-count math (Web Mercator / "slippy map" tile coordinates)
// ---------------------------------------------------------------------------

function lonToTileX(lon: number, z: number): number {
  return Math.floor(((lon + 180) / 360) * Math.pow(2, z));
}

function latToTileY(lat: number, z: number): number {
  const rad = (lat * Math.PI) / 180;
  return Math.floor(
    ((1 - Math.log(Math.tan(rad) + 1 / Math.cos(rad)) / Math.PI) / 2) *
      Math.pow(2, z),
  );
}

function tileCountForBoundsAtZoom(
  [west, south, east, north]: number[],
  z: number,
): number {
  const x0 = lonToTileX(west, z);
  const x1 = lonToTileX(east, z);
  const y0 = latToTileY(north, z); // tile Y is inverted (north → smaller index)
  const y1 = latToTileY(south, z);
  return (Math.abs(x1 - x0) + 1) * (Math.abs(y1 - y0) + 1);
}

// ---------------------------------------------------------------------------
// Service
// ---------------------------------------------------------------------------

/**
 * Thin, strongly-typed wrapper around MapLibre's `OfflineManager`.
 *
 * All offline-map operations in UI code must go through this service —
 * never import `OfflineManager` from `@maplibre/maplibre-react-native` directly
 * outside of this file.
 */
export const OfflineMapService = {
  /**
   * Create and start downloading an offline pack covering the given bounds.
   * Returns the created pack including its auto-generated UUID `id`.
   */
  async downloadRegion(args: {
    bounds: [west: number, south: number, east: number, north: number];
    metadata: OfflineMapPackMetadata;
    zoomRange?: { min: number; max: number };
    onProgress?: ProgressHandler;
    onError?: ErrorHandler;
  }): Promise<OfflinePack> {
    const zoom = args.zoomRange ?? DEFAULT_OFFLINE_ZOOM;

    const pack = await OfflineManager.createPack(
      {
        mapStyle: OPENFREEMAP_STYLE,
        bounds: args.bounds,
        minZoom: zoom.min,
        maxZoom: zoom.max,
        metadata: args.metadata,
      },
      args.onProgress as unknown as OfflinePackProgressListener,
      args.onError as unknown as OfflinePackErrorListener,
    );

    return pack;
  },

  async listPacks(): Promise<OfflinePack[]> {
    return OfflineManager.getPacks();
  },

  async getPack(id: string): Promise<OfflinePack | undefined> {
    return OfflineManager.getPack(id);
  },

  async deletePack(id: string): Promise<void> {
    OfflineManager.removeListener(id); // safe even if no listener is registered
    await OfflineManager.deletePack(id);
  },

  /**
   * Re-attach progress/error listeners to an in-flight pack.
   * Useful after the app is backgrounded and foregrounded again.
   */
  async subscribe(
    id: string,
    onProgress: ProgressHandler,
    onError: ErrorHandler,
  ): Promise<void> {
    await OfflineManager.addListener(id, onProgress, onError);
  },

  unsubscribe(id: string): void {
    OfflineManager.removeListener(id);
  },

  /**
   * Estimate the download size in bytes for a given bounds + zoom range.
   * Uses a tile-count × average-tile-size heuristic.
   *
   * OpenFreeMap vector tiles average ~30–50 KB; this uses 40 KB as the midpoint.
   */
  estimateDownloadBytes(args: {
    bounds: [west: number, south: number, east: number, north: number];
    zoomRange: { min: number; max: number };
  }): number {
    const [west, south, east, north] = args.bounds;
    let totalTiles = 0;
    for (let z = args.zoomRange.min; z <= args.zoomRange.max; z++) {
      totalTiles += tileCountForBoundsAtZoom([west, south, east, north], z);
    }
    const AVG_TILE_BYTES = 40 * 1024;
    return totalTiles * AVG_TILE_BYTES;
  },
};
